In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("Superstore.csv")

In [2]:
print(df.info())
df =df.drop(columns=["Row ID","Customer ID","Customer Name","Product ID","Product Name","Postal Code","Order ID"]
           )
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])
df["Ship Mode"].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB
None

C:\Users\Ayush\AppData\Local\Temp\ipykernel_22512\3284299870.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Order Date"] = pd.to_datetime(df["Order Date"])
C:\Users\Ayush\AppData\Local\Temp\ipykernel_22512\3284299870.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Ship Date"] = pd.to_datetime(df["Ship Date"])

array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

In [3]:
# Creating time based 
df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Day"] = df["Order Date"].dt.day
df["DayofWeek"] = df["Order Date"].dt.dayofweek

In [4]:
# Aggregation of data
daily_sales = df.groupby("Order Date")["Sales"].sum().reset_index()
# daily_sales = df.groupby("Order Date")["Sales"].sum().reset_index()
daily_sales = daily_sales.sort_values("Order Date")

daily_sales["Year"] = daily_sales["Order Date"].dt.year
daily_sales["Month"] = daily_sales["Order Date"].dt.month
daily_sales["Day"] = daily_sales["Order Date"].dt.day
daily_sales["DayofWeek"] = daily_sales["Order Date"].dt.dayofweek
# Adding lag feature
daily_sales["Lag_1"] = daily_sales["Sales"].shift(1)
daily_sales["Lag_7"] = daily_sales["Sales"].shift(7)
daily_sales["Lag_30"] = daily_sales["Sales"].shift(30)
daily_sales = daily_sales.dropna()
df1 = pd.DataFrame(daily_sales)
df1

,Order Date,Sales,Year,Month,Day,DayofWeek,Lag_1,Lag_7,Lag_30
30,2014-02-12,129.5680,2014,2,12,2,2043.4000,211.646,16.448
31,2014-02-14,576.7260,2014,2,14,4,129.5680,97.112,288.060
32,2014-02-15,21.3600,2014,2,15,5,576.7260,134.384,19.536
33,2014-02-16,9.0400,2014,2,16,6,21.3600,330.512,4407.100
34,2014-02-17,54.2080,2014,2,17,0,9.0400,180.320,87.158
...,...,...,...,...,...,...,...,...,...
1232,2017-12-26,814.5940,2017,12,26,1,2698.9270,1895.926,3666.157
1233,2017-12-27,177.6360,2017,12,27,2,814.5940,377.736,5048.172
1234,2017-12-28,1657.3508,2017,12,28,3,177.6360,2140.940,1618.254
1235,2017-12-29,2915.5340,2017,12,29,4,1657.3508,7442.021,6912.944
1236,2017-12-30,713.7900,2017,12,30,5,2915.5340,1926.776,491.888

In [5]:
df1.isnull().sum()
# df = pd.get_dummies(df, columns=["Ship Mode","Region","Category","Segment"], dtype=int)

Order Date    0
Sales         0
Year          0
Month         0
Day           0
DayofWeek     0
Lag_1         0
Lag_7         0
Lag_30        0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    9994 non-null   datetime64[ns]
 1   Ship Date     9994 non-null   datetime64[ns]
 2   Ship Mode     9994 non-null   object
 3   Segment       9994 non-null   object
 4   Country       9994 non-null   object
 5   City          9994 non-null   object
 6   State         9994 non-null   object
 7   Region        9994 non-null   object
 8   Category      9994 non-null   object
 9   Sub-Category  9994 non-null   object
 10  Sales         9994 non-null   float64
 11  Quantity      9994 non-null   int64
 12  Discount      9994 non-null   float64
 13  Profit        9994 non-null   float64
 14  Year          9994 non-null   int32
 15  Month         9994 non-null   int32
 16  Day           9994 non-null   int32
 17  DayofWeek     9994 non-null   int32
dtypes: datetime64[ns](2), float64(3), int32(4), int64(1), object(8)
memory usage: 1.2+ MB

In [7]:
df1

,Order Date,Sales,Year,Month,Day,DayofWeek,Lag_1,Lag_7,Lag_30
30,2014-02-12,129.5680,2014,2,12,2,2043.4000,211.646,16.448
31,2014-02-14,576.7260,2014,2,14,4,129.5680,97.112,288.060
32,2014-02-15,21.3600,2014,2,15,5,576.7260,134.384,19.536
33,2014-02-16,9.0400,2014,2,16,6,21.3600,330.512,4407.100
34,2014-02-17,54.2080,2014,2,17,0,9.0400,180.320,87.158
...,...,...,...,...,...,...,...,...,...
1232,2017-12-26,814.5940,2017,12,26,1,2698.9270,1895.926,3666.157
1233,2017-12-27,177.6360,2017,12,27,2,814.5940,377.736,5048.172
1234,2017-12-28,1657.3508,2017,12,28,3,177.6360,2140.940,1618.254
1235,2017-12-29,2915.5340,2017,12,29,4,1657.3508,7442.021,6912.944
1236,2017-12-30,713.7900,2017,12,30,5,2915.5340,1926.776,491.888

# EDA

In [8]:
df1.columns

Index(['Order Date', 'Sales', 'Year', 'Month', 'Day', 'DayofWeek', 'Lag_1',
       'Lag_7', 'Lag_30'],
      dtype='object')

In [9]:
# from year 2017 sales is highest , 2015 sales is lowest , from year 2014 to 2015 sales is decreasing then satrt increasing after 2015